#!/bin/sh
name="buttons"
fastbuild="0"
command="g++-10 -I./src -I/usr/local/include/SDL2 src/main.cpp -o bin/$name"
out="glog.txt"
verbose="0"
help="0"
for a in $@; do
	if [ "$a" = "-v" ]; then
		verbose="1"
	fi
	if [ "$a" = "-vw" ]; then
		verbose="2"
	fi
	if [ "$a" = "-wv" ]; then
		verbose="2"
	fi
	if [ "$a" = "help" ]; then
		help="1"
	fi
	if [ "$a" = "fast" ]; then
		fastbuild="1"
	fi
done
if [ "$help" = "1" ]; then
	echo "Options:\n(run) Run binary after building\n(commit) Commit changes to github\n(-v) Show compiler output\n(-vw) Show compiler output and log to file"
	exit
fi
if [ "$verbose" = "0" ]; then
	$command &> ./"$out"; fi
if [ "verbose" = "1" ]; then
	$command; fi
if [ "verbose" = "2" ]; then
	$command
	@command &> ./"$out"
fi
if [ "$fastbuild" = "0" ]; then
	log=$(cat "$out")
	if [ "$log" = "" ]; then
		rm "$out"
		echo "\033[0;32mBuild: no issues\033[0m"
	else
		if [ "$verbose" = "0" ]; then
			echo "\033[0;31mBuild: failed, see '"$out"'\033[0m"
		fi
	fi
fi
for a in $@; do
	if [ "$a" = "run" ]; then
		./bin/$name
	fi
	if [ "$a" = "commit" ]; then
		git add .
		git commit
		git push -u origin master >&-
	fi
done